name: validate
on:
  - push
  - pull_request

jobs:
  cache-and-install:
    name: Cache and install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup

  validate:
    needs: cache-and-install

    name: Lint and check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Lint
        shell: bash
        run: pnpm lint

      - name: Check
        shell: bash
        run: pnpm check

  unit-test:
    needs: cache-and-install

    name: Unit test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Unit test
        shell: bash
        run: pnpm test:unit

  integration-test:
    needs: cache-and-install

    name: Integration test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Setup Playwright
        shell: bash
        run: pnpm exec playwright install chromium

      - name: Integration test
        shell: bash
        run: pnpm test:integration
